#!/bin/bash

FILE=$1
if [[ -z "${FILE}" ]]
then
    echo "Usage: $0 FILE"
    exit 1
fi

if [[ ${FILE%.7z} != $FILE ]]
then
    echo "Skipping $FILE"
fi

if [[ -f ${FILE} ]]
then
    7za a ${FILE}.7z ${FILE}
    7za t ${FILE}.7z
    ls -l ${FILE} ${FILE}.7z
    rm -i ${FILE}
fi

