#!/usr/bin/perl

use warnings;
use strict;
use IO::Socket;
use Getopt::Long;

my %opts;
GetOptions(
    'host=s'    => \$opts{host},
    'port=s'    => \$opts{port},
    'timeout=s' => \$opts{timeout},
    'errors'    => \$opts{errs},
    'dtg'       => \$opts{dtg},
);

die "Usage: $0 -host=HOST -port=PORT -timeout=TIMEOUT [-dtg] [-errors]\n"
    if ! $opts{host} || ! $opts{port};

$opts{timeout} = 0 if ! $opts{timeout};

sub DEBUG {$opts{debug}}

my $socket = IO::Socket::INET->new(
    Proto     => "tcp",
    PeerAddr  => $opts{host},
    PeerPort  => $opts{port},
    Timeout   => $opts{timeout},
);

my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst)
    = gmtime(time);

if ( $socket ) {

    if ( ! $opts{errs} ) {

        printf "%4d-%02d-%02d %02d:%02d:%02d ",
            $year + 1900, $mon + 1, $mday, $hour, $min, $sec if $opts{dtg};

        print "Connected to $opts{host}:$opts{port} OK\n";

    }

    $socket->autoflush(1);

    close $socket;

} else {

    my $err = $?;
    (my $myname = $0) =~ s{^.*/}{}g;
    #
    # I want to die for the exit code, but also see the output
    #
    open(STDERR, ">&STDOUT") || die "Can't dup STDOUT: $!\n";
    my $reason = $!;
    if ( $reason eq 'Illegal seek' ) {
        $reason = 'Timeout';
    } elsif ( $reason eq 'Inappropriate ioctl for device' ) {
        $reason = 'Timeout'; # Linux
    } elsif ( $reason eq 'Invalid argument' ) {
        $reason = 'Host not found';
    }
    printf STDERR "%4d-%02d-%02d %02d:%02d:%02d ", $year + 1900, $mon + 1, $mday, $hour, $min, $sec if $opts{dtg};
    die "$myname: Can't connect to '$opts{host}:$opts{port}': $reason\n";

}

