#!/usr/bin/perl

use warnings;
use strict;
use IO::Socket;
use Getopt::Long;

my ($host, $port);

my %opts;
GetOptions(
    'h=s'   => \$host,
    'p=s'   => \$port,
    'd'   => \$opts{debug},
);

die "Usage: $0 -h HOST -p PORT [-d]\n"
    if ! $host || ! $port;

sub DEBUG {$opts{debug}}

my $socket = IO::Socket::INET->new(
    Proto     => "tcp",
    PeerAddr  => $host,
    PeerPort  => $port,
);
print "Connected to $host:$port OK\n";

die "$0: Can't connect to 'http://$host': $!\n" if ! $socket;
$socket->autoflush(1);

close $socket;

