#!/usr/bin/perl

use warnings;
use strict;
use IO::Socket;
use Getopt::Long;

my %opts;
GetOptions(
    'h=s'   => \$opts{host},
    'p=s'   => \$opts{port},
    't=s'   => \$opts{timeout},
    'd'   => \$opts{debug},
);

die "Usage: $0 -h HOST -p PORT [-d]\n"
    if ! $opts{host} || ! $opts{port};

$opts{timeout} = 0 if ! $opts{timeout};

sub DEBUG {$opts{debug}}

my $socket = IO::Socket::INET->new(
    Proto     => "tcp",
    PeerAddr  => $opts{host},
    PeerPort  => $opts{port},
    Timeout   => $opts{timeout},
);

if ( $socket ) {

    print "Connected to $opts{host}:$opts{port} OK\n";

    $socket->autoflush(1);

    close $socket;

} else {

    my $err = $?;
    (my $myname = $0) =~ s{^.*/}{}g;
    #
    # I want to die for the exit code, but also see the output
    #
    open(STDERR, ">&STDOUT") || die "Can't dup STDOUT: $!\n";
    my $reason = $!;
    $reason = 'Timeout' if $reason eq 'Illegal seek';
    die "$myname: Can't connect to '$opts{host}:$opts{port}': $reason\n";

}

