#!/usr/bin/perl
#
#
#
use warnings;
use strict;
use integer;

my $file = shift;
die "Usage: $0 FILE\n" if ! $file;

sub get_time ($) {
    my $filename = shift;
    my ($dev,$ino,$mode,$nlink,$uid,$gid,$rdev,$size,
        $atime,$mtime,$ctime,$blksize,$blocks) = stat($filename)
    or die "Can't stat '$filename': $!\n";
    return $mtime;
}

my $sec = time - get_time($file);

my $days = int($sec/(86400));
my $hours = ($sec/(3600))%24;
my $mins = ($sec/60)%60;
my $secs = $sec%60;

print "$days days $hours hours $mins mins $secs secs old\n";

