#!/bin/bash

SOURCE=$1
DEST=$2
if [[ -z "$DEST" ]]
then
    echo "Usage: $0 SOURCE_FILE DESTINATION_DIRECTORY"
    exit 1
fi

SRC_DIRNAME=$(dirname $SOURCE)
SRC_FILE=$(basename $SOURCE)

ck_dir () {
    if [[ -d $1 ]]
    then
        cd $1
        /bin/pwd
    else
        echo >&2 "ERROR: '$1' not a directory"
        exit 1
    fi
}

DEST_DIR=$(ck_dir "$DEST")
if [[ -z "$DEST_DIR" ]]
then
    echo "Usage: $0 SOURCE_FILE DESTINATION_DIRECTORY"
    exit 1
fi


if [[ -d $DEST_DIR/.git/rebase-apply ]]
then
    echo "ERROR: $DEST_DIR/.git/rebase-apply exists - aborting."
    exit 1
fi

SRC_DIR=$(ck_dir $SRC_DIRNAME)

cd $SRC_DIR

git log --pretty=email --patch-with-stat --full-index --binary --reverse -- $SRC_FILE > ~/.git.tmp.$$

cd $DEST_DIR

git am < ~/.git.tmp.$$

rm ~/.git.tmp.$$

