#!/bin/bash

for FILE in $@
do

    if [[ -e ${FILE} ]]
    then

        if [[ -f .gitignore ]]
        then

            grep "^${FILE}$" .gitignore
            if [[ $? != 0 ]]
            then

                echo ${FILE} >> .gitignore
                echo "${FILE} ignored"

            fi

        else

            echo "Please touch .gitignore"

        fi

    else

        echo "${FILE} not found"

    fi

done

