#!/usr/bin/perl
#
#
#
use warnings;
use strict;

my $cmd = '/usr/bin/git shortlog';

my %lens;
open (my $cmd_fh, "$cmd|") || die "Can't run '$cmd': $!\n";
while (defined (my $line = <$cmd_fh>)) {

    #
    next if $line !~ /^      /;
    $line =~ s/\s+$//g;
    $line =~ s/\s+(.*)$/$1/;
    $lens{length($line)}++;

}
close $cmd_fh;

for my $len ( sort { $a <=> $b } keys %lens ) {
    printf("%3d %3d %s\n", $len, $lens{$len}, "x" x $lens{$len});
}

