#!/usr/bin/perl
#
#
#
use warnings;
use strict;
use Getopt::Std;

our ($opt_h,$opt_t) = (0,"");
getopts("ht:");

print qq~<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
    "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <title>$opt_t</title>
    <link rel="stylesheet" title="style" href="style.css" type="text/css" />
  </head>

  <body>
~ if ! $opt_h;

my $link_last = 0;
while (<>) {
    chomp;
    if ( /^\s*$/ ) {
        if ( $link_last ) {
            print qq~    </ul>\n~;
            $link_last = 0;
        } else {
            print $/;
        }
    } elsif ( m{://} ) {
        if ( $link_last == 0 ) {
            print "    <ul>\n";
        }
        s{^(.*)$}{      <li><a href="$1">$1</a></li>}g;
        print "$_\n";
        $link_last = 1;
    } else {
        print "    <p>$_</p>\n";
    }
}

print qq~
  </body>
</html>
~ if ! $opt_h;

