#!/usr/bin/perl
#
#
#
use warnings;
use strict;


print qq~<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
    "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <title>Perl</title>
    <link rel="stylesheet" title="style" href="style.css" type="text/css" />
  </head>

  <body>
    <ul>
~;

while (<>) {
    chomp;
    s{^(.*)$}{      <li><a href="$1">$1</a></li>}g;
    print "$_\n";
}

print qq~    </ul>
  </body>
</html>
~;


