#!/bin/bash

NOW=$(date +'.%y%m%d.%H%M%S')
if [[ "$1" = "-n" ]]
then
    shift
    NOW=""
fi

MATCH_STRING=$1
REPLACE_WITH=$2
EDIT_FILE=$3

perl -pi${NOW} -e "s{${MATCH_STRING}}{${REPLACE_WITH}}g" ${EDIT_FILE}

