#!/usr/bin/perl -s
#
#
#
our $n; # Use $0 -n if you want package names too
use warnings;
use strict;

my $url = 'http://kernel.org/pub/software/scm/git/RPMS/x86_64/';

# Extract URLs from a specified URL
# Usage perl GETLINKS.PL url
# eg: perl getlinks.pl http://www.example.com/

use LWP::UserAgent;
use HTML::LinkExtor;
use URI::URL;
use Data::Dumper;

# Store extracted URLs in a text file
# open(OUTPUT,">getlinks.txt");


my $ua = LWP::UserAgent->new;
$ua->agent("Latest Git");

# Set up a callback that collects links
my @links = ();

# Make the parser. Unfortunately, we don't know the base yet
# (it might be diffent from $url)
my $p = HTML::LinkExtor->new(\&callback);

# Request document and parse it as it arrives
my $res = $ua->request(HTTP::Request->new(GET => $url),sub{$p->parse($_[0])});

# Expand all URLs to absolute ones
my $base = $res->base;
@links = map { $_ = url($_, $base)->abs; } @links;

sub callback {

    my($tag, %attr) = @_;
    return if $tag eq 'img'; # Ignore <img ...>

    my $link = $attr{'href'} if $attr{'href'};
    return if ! $link;
    push(@links, $link) if $link =~ /./;

}

my $pkgs;

my %links;
for my $link (@links) {

    # Make them unique
    next if $links{$link}++ > 0;

    my $line = ${$link}[0];

    chomp $line;
    if ( $line =~ m%/([^/]*$)% ) {
        my $pkg = $1;
        if ( $pkg =~ /^([^0-9]*)-([0-9].*)$/ ) {
            $pkgs->{$1}->{$2} = $line;
        }
    }

}

# Obsolete packages:
delete $pkgs->{'git-core-debuginfo'};
delete $pkgs->{'perl-Email-Valid'};

for my $pkg ( keys %$pkgs ) {

    print "# $pkg\n" if $n;

    my @pkgs = (sort keys %{$pkgs->{$pkg}} );

    print $pkgs->{$pkg}->{$pkgs[-1]}, $/;

}

