#!/usr/bin/perl
#
#
#
use warnings;
use strict;
use Getopt::Long;

my $opt;

GetOptions (
    "mac=s"    => \$opt->{mac},
    "cleaned"  => \$opt->{cleaned},
    "dhcp"     => \$opt->{dhcp},
    "nw"       => \$opt->{nw},
    "tftpboot" => \$opt->{tftpboot},
    "help"     => \$opt->{h},
    "usage"    => \$opt->{h},
)
or die("$0: ERROR: invalid command line arguments\n");

if ( $opt->{h} ) {

    die <<EOT;
Usage: $0 [-help] [-verbose] ARGUMENT
  where
    -mac MAC  - MAC addres to clean
    -cleaned  - Default
    -dhcp     - Stripped of :s
    -nw       - Output in Network (switch) aaaa.bbbb.cccc format
    -tftpboot - Stripped, with leading 1
    -help     - show this help
EOT

}

my @macs;

if ( $opt->{mac} ) {

    push (@macs, $opt->{mac});

} else {

    while (defined (my $line = <>)) {

        #
        if ( $line =~ /((\w+:){5}(\w+))/ ) {
            push (@macs, $1);
        }

    }
}

for my $mac ( @macs ) {
    my @clean;
    for my $byte ( split(/:/, $mac) ) {
        push(@clean, sprintf("%02s", lc($byte)));
    }
    my $cleaned = join(":", @clean);
    my $done = 0;
    if ( $opt->{nw} ) {
        if ( $cleaned =~ /(..):(..):(..):(..):(..):(..)/ ) {
            print "$1$2.$3$4.$5$6\n";
            $done = 1;
        }
    }
    if ( $opt->{dhcp} ) {
        print join("", @clean), $/;
        $done = 1;
    }
    if ( $opt->{tftpboot} ) {
        print "01", join("", @clean), $/;
        $done = 1;
    }
    if ( $opt->{cleaned} || $done == 0 ) {
        print "$cleaned\n";
    }
    @clean = [];
}

