#!/usr/bin/perl -ws
#
# re-hex - hexadecimal encode an ASCII url (i.e. with % signs)
# By John
#

our ($d,$s);
my $base = 'H';
if ( $d ) {
    $base = 'C';
}

while (<>){
    chomp();
    for $char (split(//,$_)) {
        if ( $s ) {
            if ( $char =~ /^[^\w\.\:\/]$/ ) {
                printf "%%%s", unpack("$base*",$char);
            } else {
                print $char;
            }
        } else {
            printf "%%%s", unpack("$base*",$char);
        }
    }
    print $/;
}

