#!/usr/bin/perl
#
#
#
use warnings;
use strict;

my $upto = shift;

LINE: while (defined (my $line = <>)) {

    #
    print "$line";
    if ( $line =~ /$upto/ ) {
        next if $. == 1;
        last LINE;
    }

}

