#!/bin/bash
#
# viw - edit script in your path
# John Harrison
#
# You may want to add:
# complete -v viw
# to your .rc files
#

for EDITOR in /usr/bin/vim /usr/local/bin/vim /usr/bin/vim $(which vim) $(which vi)
do
    if [[ -x $EDITOR ]]
    then
        break
    fi
done

case "$1" in
"-c" )
    shift
    for EDITOR in /bin/cat /usr/bin/cat $(which cat)
    do
        if [[ -x $EDITOR ]]
        then
            break
        fi
    done
;;
"-l" )
    shift
    for EDITOR in /bin/less /usr/bin/less $(which less)
    do
        if [[ -x $EDITOR ]]
        then
            break
        fi
    done
;;
esac

COMMAND=$(which $@)

if [[ -f ${COMMAND} ]]
then
    ${EDITOR} ${COMMAND}
else
    echo ${COMMAND}
fi

