#!/bin/bash
#
# viw - edit script in your path
# John Harrison
#
# You may want to add:
# complete -v viw
# to your .rc files
#

EDITOR=/usr/bin/vi

if [[ -x /usr/bin/vim ]]
then
    EDITOR=/usr/bin/vim
fi

if [[ "$1" = "-c" ]]
then
    shift
    if [[ -x /bin/cat ]]
    then
        EDITOR=/bin/cat
    elif [[ -x /usr/bin/cat ]]
    then
        EDITOR=/usr/bin/cat
    else
        EDITOR=$(which cat)
    fi
fi

COMMAND=$(which $@)

if [[ -f ${COMMAND} ]]
then
    ${EDITOR} ${COMMAND}
else
    echo ${COMMAND}
fi

